source 'https://github.com/mustachedk/MustachePodSpec.git'
source 'https://github.com/cocoapods/specs.git'


platform :ios, '11.0'

use_frameworks!

target 'MustacheUIKit_Example' do
  pod 'MustacheUIKit', :path => '../'

  target 'MustacheUIKit_Tests' do
    inherit! :search_paths

    
  end
end
